name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (ruff)
        run: ruff --format=github .

      - name: Format check (black)
        run: black --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Tests (pytest)
        run: pytest -q
